apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
    name: myapp
    labels:
      app: myapp
      type: front-end
    spec:
      containers:
      - name: myapp
        image: nginx
  selector:
    matchLabels:
      type: front-end
